sudo: required

language: node

branches:
  only:
  - master
    
services:
  - docker
  
jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t test .
      - docker images
      - docker tag test:"$DOCKER_IMAGE_TAG" $DOCKER_USERNAME/test:"$DOCKER_IMAGE_TAG"
      - docker push $DOCKER_USERNAME/test:"$DOCKER_IMAGE_TAG"
    - stage: Upgrade Rancher Service 
      script: 
      - bash ./build.sh
    


      
 
