sudo: required

language: node

branches:
  only:
  - master
    
services:
  - docker
  
jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t test:dev .
      - docker images
      - docker tag test:dev $DOCKER_USERNAME/test:dev
      - docker push $DOCKER_USERNAME/test:dev
    


      
 
