sudo: required

language: node

branches:
  only:
  - master
    
services:
  - docker
  
jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - stage: Upgrade Rancher Service 
      script: 
      - bash ./build.sh
    


      
 
