sudo: required

language: node

services:
  - docker
  
jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t test .
      - docker images
      - docker tag test $DOCKER_USERNAME/test
      - docker push $DOCKER_USERNAME/test
    - stage: test
      script: 
      - bash build.sh
      
 
