sudo: required

language: node

branches:
  only:
  - master
    
services:
  - docker
  
jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t test .
      - docker images
      - docker tag test $DOCKER_USERNAME/test
      - docker push $DOCKER_USERNAME/test
    - stage: build next docker image
      script:
      - docker build -t test .
      - docker images
      - docker tag test $DOCKER_USERNAME/test
      - docker push $DOCKER_USERNAME/test


      
 
