sudo: required

language: node

branches:
  only:
  - master
    
services:
  - docker
  
jobs:
  include:
    - stage: Upgrade Rancher Service 
      script: 
      - echo "'http://localhost:8087/v2-beta/projects/1a29/services/"'"$ID"'"?action=upgrade'"
  


      
 
