sudo: required

language: node

branches:
  only:
  - master
    
services:
  - docker
  
jobs:
  include:
    - stage: Upgrade Rancher Service 
      script: 
      - bash ./build.sh
    


      
 
